# Database configuration
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# H2 Console (for debugging)
spring.h2.console.enabled=true

# Flyway configuration
spring.flyway.clean-disabled=false
spring.flyway.clean-on-validation-error=true
spring.flyway.locations=classpath:db/migration
spring.modulith.runtime.flyway-enabled=true

# Modulith configuration
spring.modulith.enable-jmx-support=false

